// <auto-generated />
using CheckoutAPI.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckoutAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260414215107_AddIdempotentRequestTable")]
    partial class AddIdempotentRequestTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckoutAPI.Domain.IdempotentRequest", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusType")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("IdempotentRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
